CREATE TABLE Class1 (Id1 int(11) NOT NULL AUTO_INCREMENT, Text varchar(255), PRIMARY KEY (Id1)) ENGINE=InnoDB;
CREATE TABLE Class2 (Id2 int(11) NOT NULL AUTO_INCREMENT, Class1Id1 int(11) NOT NULL, SomeNum float NOT NULL, PRIMARY KEY (Id2)) ENGINE=InnoDB;
ALTER TABLE Class2 ADD INDEX FKClass294130 (Class1Id1), ADD CONSTRAINT FKClass294130 FOREIGN KEY (Class1Id1) REFERENCES Class1 (Id1);
